# Generated by Django 5.1.4 on 2025-01-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': [('special_status', 'Can check the details of each meal')]},
        ),
    ]
