# Generated by Django 5.1.4 on 2025-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
