services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=django_website.settings
      - DJANGO_SECRET_KEY=p_Q+c39&#8'qRhqTN'QWJwwr'EM4[UR@,iQ9p^P9
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: