# Generated by Django 5.1.4 on 2025-01-23 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='O código postal deve estar no formato XXXX-XXX.', regex='^\\d{4}-\\d{3}$')])),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O número de telemóvel deve conter exatamente 9 dígitos.', regex='^\\d{9}$')])),
                ('nif', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O NIF deve conter exatamente 9 dígitos.', regex='^\\d{9}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
