# Generated by Django 5.1.4 on 2025-01-31 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilling',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Definir como perfil de faturação padrão'),
        ),
        migrations.AddField(
            model_name='userbilling',
            name='name',
            field=models.CharField(help_text='Nome do perfil de faturação', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
