# Generated by Django 5.1.4 on 2025-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Open', max_length=10),
        ),
    ]
